---
- name: power off vm
  vars: 
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  vsphere_guest: 
    vcenter_hostname: "{{ esxi_host.vcenter_server.hostname }}"
    username: "{{ esxi_host.vcenter_server.username }}"
    password: "{{ esxi_host.vcenter_server.password }}"
    guest: "{{ vmname }}"
    validate_certs: no
    state: powered_off
    force: yes

- name: wait for power off to finish
  pause: seconds=10

- name: Delete vm
  vars: 
    vmname: "ContrailVM-{{ esxi_host.vcenter_server.datacentername }}-{{ esxi_host.name }}"
  vsphere_guest:
    vcenter_hostname: "{{ esxi_host.vcenter_server.hostname }}"
    username: "{{ esxi_host.vcenter_server.username }}"
    password: "{{ esxi_host.vcenter_server.password }}"
    guest: "{{ vmname }}"
    validate_certs: no
    state: absent
    force: yes

