deployment:
  type:
    contrail:
      branch: master
      registry: svl-artifcatory.juniper.net/contrail-nightly
    kolla:
      branch:
      registry: 10.84.5.85:5010
  version:
  sku: ocata
  os: ubuntu
  deployer: contrail-ansible-deployer
  orchestrator: openstack

provider_config:
  bms:
    ssh_pwd: c0ntrail123
    ssh_user: root
    ntpserver: 10.84.5.100
    domainsuffix: local

contrail_configuration:
  AAA_MODE: rbac
  RABBITMQ_NODE_PORT: 5673
  LOG_LEVEL: SYS_DEBUG
  SSL_ENABLE: True
  METADATA_SSL_ENABLE: True
  INTROSPECT_SSL_ENABLE: True
  XMPP_SSL_ENABLE: True
  SANDESH_SSL_ENABLE: True
  RABBITMQ_USE_SSL: True
  CASSANDRA_SSL_ENABLE: True
  KAFKA_SSL_ENABLE: True
  ssh_user: root
  ssh_pwd: c0ntrail123

orchestrator_configuration:
  keystone:
    version: v3
    password: c0ntrail123

kolla_config:
 kolla_globals:
   openstack_release: rocky
   #enable_haproxy: yes
   #kolla_internal_vip_address: 10.10.0.100
   #kolla_external_vip_address: 10.87.118.222
   #enable_haproxy: yes
   enable_ironic: yes
   enable_swift: yes
   #keepalived_virtual_router_id: 125
 kolla_passwords:
   keystone_admin_password: contrail123
   metadata_secret: c0ntrail123

test_configuration:
  image_web_server: 10.84.5.120
  use_project_scoped_token: True
  web_server:
    server: zephyrine.englab.juniper.net
    username: stack
    password: stack@123
    report_path:
    log_path: /var/www/html/Docs/logs
    web_root: /Docs/logs
  mail_server:
    server: 10.84.24.64
    port: 4000
    to: dl-contrail-sw@juniper.net
    sender: contrail-build@juniper.net
