deployment:
    type:
        kolla:
            branch: contrail/ocata
            registry: ci-repo.englab.juniper.net:5000
        contrail:
            branch: R5.0
            registry: ci-repo.englab.juniper.net:5000
    sku: ocata
    os: centos7
    version: ocata-5.0-19
    orchestrator: openstack
    deployer: contrail_command

provider_config:
  bms:
    ssh_pwd: c0ntrail123
    ssh_user: root
    ntpserver: 10.84.5.100
    domainsuffix: local
instances:
  Control155:
    provider: bms
    ip: 10.87.74.155
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      openstack:

#  Control152:
#    provider: bms
#    ip: 10.87.74.152
#    roles:
#      config_database:
#      config:
#      control:

#  Control153:
#    provider: bms
#    ip: 10.87.74.153
#    roles:
#      config_database:
#      config:
#      control:

  TSN159:
    provider: bms
    ip: 10.87.74.159
    roles:
      vrouter:
          TSN_EVPN_MODE: True

  TSN154:
    provider: bms
    ip: 10.87.74.154
    roles:
      contrail_command:

  Compute148:
    provider: bms
    ip: 10.87.74.148
    roles:
      vrouter:
      openstack_compute:

global_configuration:
  CONTAINER_REGISTRY: ci-repo.englab.juniper.net:5010
  REGISTRY_PRIVATE_INSECURE: True

contrail_configuration:
  CONTRAIL_VERSION: ocata-5.0-19
  CONTROLLER_NODES: 172.17.90.4
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  VROUTER_GATEWAY: 172.17.90.254
  KEYSTONE_AUTH_ADMIN_PASSWORD: contrail123
  KEYSTONE_AUTH_HOST: 172.17.90.161
  KEYSTONE_AUTH_URL_VERSION: /v3
  TSN_NODES: 172.17.90.5
  ENCAP_PRIORITY: "VXLAN,MPLSoUDP,MPLSoGRE"
  METADATA_PROXY_SECRET: contrail123

kolla_config:
  kolla_globals:
    kolla_internal_vip_address: 172.17.90.161
    contrail_api_interface_address: 172.17.90.4
    kolla_external_vip_address: 10.87.74.161
    enable_haproxy: "yes"
  kolla_passwords:
    keystone_admin_password: contrail123
    metadata_secret: contrail123

orchestrator_configuration:
  keystone:
    version: v3
    password: contrail123
  internal_vip: 172.17.90.161
  external_vip: 10.87.74.161

test_configuration:
    image_web_server: 10.84.5.120
    use_project_scoped_token: True
    public_host: 10.84.5.120
    web_server:
        server:
        username:
        password:
        report_path:
        log_path:
        web_root:
    mail_server:
        server:
        port:
        to:
        sender:

    physical_routers:
      5c3-mx80-2:
        vendor: juniper
        mode: mx
        asn: 64513
        name: 5c3-mx80-2
        ssh_username: root
        ssh_password: Embe1mpl
        mgmt_ip: 10.84.130.55
        tunnel_ip: 7.7.7.77
        ports: xe-0/0/0
        type: router

      5c3-qfx3:
        vendor: juniper
        model: qfx5100
        asn: 64513
        name: 5c3-qfx3
        ssh_username: root
        ssh_password: Embe1mpls
        mgmt_ip: 10.84.130.48
        tunnel_ip: 3.3.3.3
        ports: xe-0/0/1
        type: tor

      5c3-qfx4:
        vendor: juniper
        model: qfx5100
        asn: 64513
        name: 5c3-qfx4
        ssh_username: root
        ssh_password: Embe1mpls
        mgmt_ip: 10.84.130.49
        tunnel_ip: 4.4.4.4
        ports: xe-0/0/1
        type: tor

    tor_hosts:
       172.17.90.4:
        tor_port: xe-0/0/1
        host_port: p5p2
        mgmt_ip: 10.87.74.141
        username: root
        password: c0ntrail123

       172.17.90.3:
        tor_port: xe-0/0/1
        host_port: p5p1
        mgmt_ip: 10.87.74.141
        username: root
        password: c0ntrail123



bms_reimage_info:
  server_manager:
    ip:
    username:
    password:


vm_info:
  default:
    image_dest: /mnt/disk1/images/
    disk_format: qcow2
    image_source: http://10.84.5.120/images/centos-7.5-copy.qcow2.gz
  hypervisors:
    kvm_5c3s29_2:
      username: root
      ip: 10.87.74.138
      password: c0ntrail123
      vm_config:
        host4:
          name: Control155
          ram: 65536
          vcpus: 8
          server: kvm_5c3s29_2
          network:
            interfaces:
              intf1:
                bridge: br0
                mac: '62:53:55:02:00:03'
                model: virtio
              intf2:
                bridge: br1
                model: virtio
        host5:
          name: TSN159
          ram: 16385
          vcpus: 8
          server: kvm_5c3s29_2
          network:
            interfaces:
              intf1:
                bridge: br0
                mac: '62:53:55:02:00:04'
                model: virtio
              intf2:
                bridge: br1
                model: virtio

        host6:
          name: Compute148
          ram: 16385
          vcpus: 8
          server: kvm_5c3s29_2
          network:
            interfaces:
              intf1:
                bridge: br0
                mac: '62:53:55:02:01:00'
                model: virtio
              intf2:
                bridge: br1
                model: virtio

    kvm_5c3s29_3:
      username: root
      ip: 10.87.74.139
      password: c0ntrail123
      vm_config:
        host7:
          name: Control152
          ram: 32710
          vcpus: 8
          server: kvm_5c3s29_3
          network:
            interfaces:
              intf1:
                bridge: br0
                mac: '62:53:55:02:02:01'
                model: virtio
              intf2:
                bridge: br1
                model: virtio
        host8:
          name: Control153
          ram: 32710
          vcpus: 8
          server: kvm_5c3s29_3
          network:
            interfaces:
              intf1:
                bridge: br0
                mac: '62:53:55:02:02:02'
                model: virtio
              intf2:
                bridge: br1
                model: virtio

        host9:
          name: TSN154
          ram: 16385
          vcpus: 8
          server: kvm_5c3s29_3
          network:
            interfaces:
              intf1:
                bridge: br0
                mac: '62:53:55:02:02:03'
                model: virtio
              intf2:
                bridge: br1
                model: virtio



control_data:
    host4:
      ip: 10.87.74.155
      ctrldata_ip: 172.17.90.4
      prefix: 24
      gw: 172.17.90.254
      device: eth1
    host5:
      ip: 10.87.74.159
      ctrldata_ip: 172.17.90.5
      prefix: 24
      gw: 172.17.90.254
      device: eth1
    host6:
      ip: 10.87.74.148
      ctrldata_ip: 172.17.90.6
      prefix: 24
      gw: 172.17.90.254
      device: eth1
    host7:
      ip: 10.87.74.152
      ctrldata_ip: 172.17.90.8
      prefix: 24
      gw: 172.17.90.254
      device: eth1
    host8:
      ip: 10.87.74.153
      ctrldata_ip: 172.17.90.9
      prefix: 24
      gw: 172.17.90.254
      device: eth1
    host9:
      ip: 10.87.74.154
      ctrldata_ip: 172.17.90.10
      prefix: 24
      gw: 172.17.90.254
      device: eth1
