---
vcenter_servers:
  - server1:
      hostname: 10.204.217.246
      username: administrator@vsphere.local
      password: Contrail123!
      # Optional: defaults to False
      #validate_certs: False
      datacentername: "c4_datacenter11"
      clusternames:
        - "c4_cluster11"
        - "c4_cluster12"
      # Optional: If not specified default vm_dvs switch is created. This is the dvswitch for providing contrail overlay networking support for vcenter guest VMs.
      dv_switch:
        dv_switch_name: c4k4_dvs
      dv_port_group:
        dv_portgroup_name: c4k4u14_dvpg
        number_of_ports: 1800
      # Optional: Specify the control-data DVswitch and PG
      #dv_switch_control_data:
      #  dv_switch_name:
      #dv_port_group_control_data:
      #  dv_portgroup_name:
      #  number_of_ports:
      #  uplink:
      # Optional: Specify the mgmt DVswitch and PG
      #dv_switch_mgmt:
      #  dv_switch_name:
      #dv_port_group_mgmt:
      #  dv_portgroup_name:
      #  number_of_ports:
      #  uplink:
      # Optional: The user is exepcted to pre-create this switch and pre-configure sriov related items in vcenter/esxi, PG is created by the playbook
      #dv_switch_sr_iov:
      #  dv_switch_name:
      #dv_port_group_sriov:
      #  dv_portgroup_name:
      #  number_of_ports:
esxihosts:
  - name: 10.204.216.224
    username: root
    password: c0ntrail123
    # Optional: defaults to False
    #validate_certs: False
    datastore: k4-ds
    datacenter: "c4_datacenter11"
    cluster: "c4_cluster11"

    # Optional: specify std switch name (pre-configured), pg name specified here will be created, default switch_name is vswitch0 and pg is fab-pg
    #std_switch_list:
    #  - pg_name: mgmt-pg
    #    switch_name: vSwitch0
    contrail_vm:
      vmdk: /root/ContrailVMCentOS74-ovf.tar
      networks: 
        - mac: 00:50:56:aa:aa:03
          # options: standard/dvs, defaults to standard
          #sw_type: standard
          # standard or dvs name, defaults to vSwitch0
          #switch_name: vSwitch0
          # defaults to contrail-pg
          #pg: mgmt-pg
      # List of sriov nics to add to the computeVM. dv_switch_sr_iov stanza is required to be specified in vcenter block. User is expected to preconfigure this dvswitch. Assiciated portgroup is created by SM provisioning
        #sr_iov_nics:
      #  - dev1
      #  - dev2
      # List of PCI nics to add to the computeVM. User is expected to pre-configure pci pass-through on esxi host
      #pci_devices:
      #  - 0000:04:00.0
      #  - 0000:04:00.1
    vcenter_server: server1
  - name: 10.204.216.225
    username: root
    password: c0ntrail123
    # Optional: defaults to False
    #validate_certs: False
    datastore: k5-ds
    datacenter: "c4_datacenter11"
    cluster: "c4_cluster11"

    # Optional: specify std switch name (pre-configured), pg name specified here will be created, default switch_name is vswitch0 and pg is fab-pg
    #std_switch_list:
    #  - pg_name: mgmt-pg
    #    switch_name: vSwitch0
    contrail_vm:
      vmdk: /root/ContrailVMCentOS74-ovf.tar
      networks: 
        - mac: 00:50:56:aa:aa:04
          # options: standard/dvs, defaults to standard
          #sw_type: standard
          # standard or dvs name, defaults to vSwitch0
          #switch_name: vSwitch0
          # defaults to contrail-pg
          #pg: mgmt-pg
    # List of sriov nics to add to the computeVM. dv_switch_sr_iov stanza is required to be specified in vcenter block. User is expected to preconfigure this dvswitch. Assiciated portgroup is created by SM provisioning
      #sr_iov_nics:
      #  - dev1
      #  - dev2
      # List of PCI nics to add to the computeVM. User is expected to pre-configure pci pass-through on esxi host
      #pci_devices:
      #  - 0000:04:00.0
      #  - 0000:04:00.1
    vcenter_server: server1
  - name: 10.204.216.226
    username: root
    password: c0ntrail123
    # Optional: defaults to False
    #validate_certs: False
    datastore: k6-ds
    datacenter: "c4_datacenter11"
    cluster: "c4_cluster11"

    # Optional: specify std switch name (pre-configured), pg name specified here will be created, default switch_name is vswitch0 and pg is fab-pg
    #std_switch_list:
    #  - pg_name: mgmt-pg
    #    switch_name: vSwitch0
    contrail_vm:
      vmdk: /root/ContrailVMCentOS74-ovf.tar
      networks: 
        - mac: 00:50:56:aa:aa:05
          # options: standard/dvs, defaults to standard
          #sw_type: standard
          # standard or dvs name, defaults to vSwitch0
          #switch_name: vSwitch0
          # defaults to contrail-pg
          #pg: mgmt-pg
    # List of sriov nics to add to the computeVM. dv_switch_sr_iov stanza is required to be specified in vcenter block. User is expected to preconfigure this dvswitch. Assiciated portgroup is created by SM provisioning
      #sr_iov_nics:
      #  - dev1
      #  - dev2
      # List of PCI nics to add to the computeVM. User is expected to pre-configure pci pass-through on esxi host
      #pci_devices:
      #  - 0000:04:00.0
      #  - 0000:04:00.1
    vcenter_server: server1
