- hosts: localhost
  gather_facts: no
  tasks:
    - add_host:
        name: "{{ item.value.ip }}"
        ansible_ssh_host: "{{ item.value.ip }}"
        ansible_ssh_user: "{{ item.value.ansible_user | default('root') }}"
        ansible_ssh_pass: "{{ item.value.ansible_ssh_pass | default('c0ntrail123') }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        group: "container_hosts"
      with_dict: "{{ instances }}"

- hosts: localhost
  gather_facts: no
  environment:
    CT_MX_GW_TEST: "{{ lookup('env', 'CT_MX_GW_TEST') }}"
    CT_EMAIL_SUBJECT: "{{ lookup('env', 'CT_EMAIL_SUBJECT') }}"
    CT_SKU: "{{ deployment.sku }}"
  roles:
  - run_tempest

